version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9
      - image: circleci/postgres:10.6
        environment:
          POSTGRES_USER: prime
          POSTGRES_DB: prime-tests
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run lerna bootstrap
      - run: yarn test
      - run: yarn codecov
